# Generated by Django 4.1.7 on 2023-03-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('P', 'Paypal'), ('S', 'Strip')], max_length=1, null=True),
        ),
    ]
