# Generated by Django 4.1.7 on 2023-03-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_stripe_charge_id_payment_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
